import { useEffect, useMemo, useRef, useState } from 'react';
import { ArrowLeft, ArrowRight, Building2, Footprints, Layers, PersonStanding, RotateCcw, Save, X } from 'lucide-react';
import Viewer, { type DropRequest, type WalkLocation } from './Viewer';
import type { Building, Graph, Node, ZoneView } from './data.ts';
import { canEditFirebase } from './firebase.ts';
import { checkEdge, pointOnFloor } from './geometry.ts';
import { addWaypoint, connectWaypoints, deleteWaypoint, disconnectWaypoints, updateWaypoint, validateGraph } from './graphEdit.ts';
import { copyGraph, createGraphStore, type GraphSnapshot } from './graphStore.ts';
import { findRoute } from './routing.ts';

type Props = { building: Building; onBack: () => void; onUpdate: (building: Building) => void; onDirtyChange?: (dirty:boolean)=>void };
type Mode = 'local' | 'firebase';
type Tool = 'select' | 'add' | 'move';
type Status = 'loading' | 'saved' | 'unsynced' | 'saving' | 'failed' | 'conflict';
const types = ['entrance','hallway','stairs','destination','door','opening','waypoint'];
const draftKey = (b: Building, mode: Mode) => ['gnarly-draft',mode,b.id,b.activeVersion||'sample',b.zoneId||'root'].join(':');
const title = (node: Node) => (node.label ? node.label + ' · ' : '') + node.id;
function Picker({ caption, nodes, value, change }: { caption: string; nodes: Node[]; value: string; change: (value: string) => void }) {
  const [query,setQuery] = useState('');
  const visible=nodes.filter(node=>title(node).toLowerCase().includes(query.toLowerCase()));
  return <label className="waypoint-picker">{caption}<input aria-label={'Search '+caption} placeholder="Search waypoints" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label={caption} value={value} onChange={e=>change(e.target.value)}><option value="">Choose waypoint</option>{visible.map(node=><option key={node.id} value={node.id}>{title(node)}</option>)}{value&&!visible.some(node=>node.id===value)&&<option value={value}>{value}</option>}</select></label>;
}
export default function BuildingWorkspace({building,onBack,onUpdate,onDirtyChange}:Props) {
  const [mode,setMode]=useState<Mode>(building.demo||!canEditFirebase()?'local':'firebase');
  const store=useMemo(()=>createGraphStore(building,mode),[building.id,building.activeVersion,building.zoneId,mode]);
  const [base,setBase]=useState<GraphSnapshot|null>(null),[draft,setDraft]=useState<Graph|null>(null),[remote,setRemote]=useState<GraphSnapshot|null>(null);
  const baseRef=useRef<GraphSnapshot|null>(null),savingRef=useRef(false);
  const [status,setStatus]=useState<Status>('loading'),[error,setError]=useState(''),[notice,setNotice]=useState('');
  const [editing,setEditing]=useState(false),[tool,setTool]=useState<Tool>('select'),[selectedId,setSelectedId]=useState(''),[target,setTarget]=useState('');
  const [floor,setFloor]=useState('all'),[start,setStart]=useState(''),[destination,setDestination]=useState(''),[showRoute,setShowRoute]=useState(false),[step,setStep]=useState(0),[playing,setPlaying]=useState(false),[reset,setReset]=useState(0);
  const [walker,setWalker]=useState<WalkLocation|null>(null),[walking,setWalking]=useState(false),[placingWalker,setPlacingWalker]=useState(false),[walkDrop,setWalkDrop]=useState<DropRequest|null>(null),[draggingWalker,setDraggingWalker]=useState(false);
  const [form,setForm]=useState({name:'',type:'waypoint',floor:'',x:'',y:'',z:''});
  const graph=draft||building.graph!; const scan=building.scan; const key=draftKey(building,mode);
  const dirty=Boolean(base&&draft&&JSON.stringify(base.graph)!==JSON.stringify(draft));
  const selected=graph.nodes.find(node=>node.id===selectedId);
  const route=useMemo(()=>showRoute?findRoute({graph,startId:start,destinationId:destination,options:{scan}}):null,[graph,start,destination,showRoute,scan]);
  const blocked=useMemo(()=>graph.edges.filter(edge=>checkEdge(edge,graph,scan).status==='blocked'),[graph,scan]);
  const newBlocked=useMemo(()=>{const previous=new Set((base?.graph.edges||[]).filter(edge=>checkEdge(edge,base!.graph,scan).status==='blocked').map(edge=>JSON.stringify(edge)));return blocked.filter(edge=>!previous.has(JSON.stringify(edge)))},[base,blocked,scan]);
  const unverified=useMemo(()=>graph.edges.filter(edge=>checkEdge(edge,graph,scan).status==='unverified').length,[graph,scan]);
  const issues=useMemo(()=>validateGraph(graph),[graph]);
  useEffect(()=>onDirtyChange?.(dirty),[dirty,onDirtyChange]);
  useEffect(()=>{
    let live=true;baseRef.current=null;setStatus('loading');setBase(null);setDraft(null);setRemote(null);setError('');setEditing(false);setShowRoute(false);
    function received(snapshot:GraphSnapshot){
      if(!live||savingRef.current||baseRef.current?.revision===snapshot.revision)return;
      const saved=localStorage.getItem(key);
      if(saved){try{const local=JSON.parse(saved) as {base:GraphSnapshot;graph:Graph};if(JSON.stringify(local.base.graph)!==JSON.stringify(local.graph)){
        baseRef.current=local.base;setBase(local.base);setDraft(local.graph);setRemote(local.base.revision===snapshot.revision?null:snapshot);setStatus(local.base.revision===snapshot.revision?'unsynced':'conflict');return;
      }}catch{localStorage.removeItem(key)}}
      baseRef.current=snapshot;setBase(snapshot);setDraft(copyGraph(snapshot.graph));setRemote(null);setStatus('saved');
      setStart(snapshot.graph.nodes.find(node=>node.type==='entrance')?.id||snapshot.graph.nodes[0]?.id||'');
      setDestination(snapshot.graph.nodes.find(node=>node.type==='destination')?.id||snapshot.graph.nodes.at(-1)?.id||'');
    }
    store.load().then(received).catch(e=>{if(live){setError(String(e));setStatus('failed')}});
    const unsubscribe=store.subscribe(received,e=>{if(live)setError(e.message)});
    return()=>{live=false;unsubscribe()};
  },[store,key]);
  useEffect(()=>{if(!base||!draft)return;if(dirty)localStorage.setItem(key,JSON.stringify({base,graph:draft}));else localStorage.removeItem(key)},[base,draft,dirty,key]);
  useEffect(()=>{if(!dirty)return;const guard=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue=''};window.addEventListener('beforeunload',guard);return()=>window.removeEventListener('beforeunload',guard)},[dirty]);
  useEffect(()=>{if(!playing||!route?.ok)return;const timer=window.setTimeout(()=>{if(step>=route.nodes.length-1){setPlaying(false);return}setStep(step+1);setFloor(route.nodes[step+1].floor)},850);return()=>window.clearTimeout(timer)},[playing,route,step]);
  useEffect(()=>{if(selected)setForm({name:selected.label||'',type:selected.type,floor:selected.floor,x:String(selected.position[0]),y:String(selected.position[1]),z:String(selected.position[2])})},[selectedId,selected?.position,selected?.label,selected?.type,selected?.floor]);
  function change(next:Graph,message=''){setDraft(next);setNotice(message);setError('');setPlaying(false);setStep(0);if(status!=='conflict')setStatus('unsynced')}
  function leave(){if(dirty&&!window.confirm('Leave with unsaved edits? Your draft will remain in this browser.'))return;onBack()}
  function zoneChange(zone:ZoneView){if(dirty&&!window.confirm('Switch zones? Your unsaved draft will remain in this browser.'))return;onUpdate({...building,zoneId:zone.id,graph:zone.graph,scan:zone.scan,graphPath:zone.graphPath,notice:zone.notice})}
  function modeChange(next:Mode){if(next===mode)return;if(dirty&&!window.confirm('Switch data modes? Your unsaved draft will remain in this browser.'))return;setMode(next)}
  function floorPick(position:[number,number,number],floorId:string){
    if(!editing||tool==='select')return;
    const nearest=graph.nodes.filter(node=>node.floor===floorId).sort((a,b)=>Math.hypot(a.position[0]-position[0],a.position[2]-position[2])-Math.hypot(b.position[0]-position[0],b.position[2]-position[2]))[0];
    const point:[number,number,number]=[position[0],nearest?.position[1]??position[1],position[2]];
    if(!pointOnFloor(point,floorId,graph,scan)){setError('Pick a position on the displayed floor.');return}
    try{if(tool==='add'){const id='wp-'+crypto.randomUUID().slice(0,8);change(addWaypoint(graph,{id,floor:floorId,type:'waypoint',position:point,label:'',source:'manual'},scan),'Waypoint added. Connect it to walkable neighbors.');setSelectedId(id)}
    else if(selected){const result=updateWaypoint(graph,{...selected,floor:floorId,position:point},scan);if(result.removedEdges.length&&!window.confirm('Moving removes '+result.removedEdges.length+' blocked connection(s). Continue?'))return;change(result.graph,result.removedEdges.length+' affected connection(s) removed.')}setTool('select')}catch(e){setError(String(e))}
  }
  function placeWalker(location:WalkLocation|null){
    setDraggingWalker(false);
    if(!location){setError('Drop the person onto a visible floor inside the building.');return}
    const floorInfo=graph.floors.find(item=>item.id===location.floorId);
    const position:[number,number,number]=[location.position[0],floorInfo?.elevation??location.position[1],location.position[2]];
    if(!pointOnFloor(position,location.floorId,graph,scan)){setError('Drop the person onto a walkable part of the floor.');return}
    setWalker({position,floorId:location.floorId});setFloor(location.floorId);setWalking(true);setPlacingWalker(false);setPlaying(false);setError('');
  }
  function viewerFloorPick(position:[number,number,number],floorId:string){if(placingWalker)placeWalker({position,floorId});else floorPick(position,floorId)}
  function walkKey(code:string,down:boolean){window.dispatchEvent(new KeyboardEvent(down?'keydown':'keyup',{code,bubbles:true}))}
  function applyForm(){if(!selected)return;const position=[Number(form.x),Number(form.y),Number(form.z)] as [number,number,number];if([form.x,form.y,form.z].some(x=>x.trim()==='')||!position.every(Number.isFinite)){setError('Enter valid X, Y, Z coordinates.');return}
    try{const result=updateWaypoint(graph,{...selected,label:form.name.trim()||null,type:form.type,floor:form.floor,position},scan);if(result.removedEdges.length&&!window.confirm('This edit removes '+result.removedEdges.length+' blocked connection(s). Continue?'))return;change(result.graph,result.removedEdges.length?result.removedEdges.length+' blocked connection(s) removed.':'Waypoint updated.')}catch(e){setError(String(e))}}
  function remove(){if(!selected)return;const count=graph.edges.filter(edge=>edge.from===selected.id||edge.to===selected.id).length;if(!window.confirm('Delete '+selected.id+(count?' and its '+count+' connection(s)':'')+'?'))return;change(deleteWaypoint(graph,selected.id).graph,'Waypoint deleted.');setSelectedId('')}
  async function save(){if(!base||!draft)return;if(issues.length||newBlocked.length){setError('Resolve '+issues.length+' graph error(s) and '+newBlocked.length+' newly blocked connection(s) before saving.');return}if(remote){setStatus('conflict');return}savingRef.current=true;setStatus('saving');setError('');try{const saved=await store.save(draft,base);baseRef.current=saved;setBase(saved);setDraft(copyGraph(saved.graph));setStatus('saved');localStorage.removeItem(key);setNotice(mode==='firebase'?'Saved to Firebase.':'Saved in this browser only · not synced.');if(mode==='firebase')onUpdate({...building,graph:saved.graph,graphPath:saved.path})}catch(e){setStatus('failed');setError(String(e))}finally{savingRef.current=false;if(mode==='firebase')void store.load().then(latest=>{if(latest.revision!==baseRef.current?.revision){setRemote(latest);setStatus('conflict')}}).catch(()=>{})}}
  function cancel(){if(!base)return;setDraft(copyGraph(base.graph));setSelectedId('');setError('');setNotice('Restored last saved graph.');setStatus('saved');localStorage.removeItem(key)}
  function resolveConflict(useRemote:boolean){if(!remote)return;if(useRemote){if(!window.confirm('Discard your draft and load the remote graph?'))return;baseRef.current=remote;setBase(remote);setDraft(copyGraph(remote.graph));localStorage.removeItem(key);setStatus('saved')}
    else{if(!window.confirm('This will keep your complete draft as the next graph. Changes made in the remote graph since you started will not appear in it. The previous graph file remains in Storage. Continue only after reviewing both versions.'))return;baseRef.current=remote;setBase(remote);setStatus('unsynced');setNotice('Your draft is based on the latest revision. Review all connections before saving; the prior graph file remains in Storage.')}setRemote(null)}
  return <main className="inside"><div className="viewer-top"><div><button className="back" onClick={leave}><ArrowLeft size={17}/> Back to map</button><div className="viewer-title"><span>BUILDING EXPLORER</span><h1>{building.name}</h1></div></div><div className="viewer-badge"><span/> {building.demo?'SAMPLE EXPERIENCE':'LIVE BUILDING'}</div></div>
    <div className={'viewer '+(draggingWalker?'walker-dragging ':'')+(walking?'walking-view':'')} onDragOver={e=>{if(e.dataTransfer.types.includes('application/x-gnarly-walker')){e.preventDefault();e.dataTransfer.dropEffect='copy';setDraggingWalker(true)}}} onDragLeave={e=>{if(!e.currentTarget.contains(e.relatedTarget as globalThis.Node|null))setDraggingWalker(false)}} onDrop={e=>{if(!e.dataTransfer.types.includes('application/x-gnarly-walker'))return;e.preventDefault();setWalkDrop({clientX:e.clientX,clientY:e.clientY,id:Date.now()})}}>
      <Viewer graph={graph} scan={scan} illustrative={Boolean(building.demo)} floor={floor} selected={selectedId||destination} onSelect={id=>{setSelectedId(id);setPlaying(false)}} path={route?.ok?route.nodes:[]} step={step} reset={reset} editing={editing} onFloorPick={editing||placingWalker?viewerFloorPick:undefined} walker={walker} walking={walking} dropRequest={walkDrop} onWalkerDrop={placeWalker} onWalkerMove={setWalker}/>
      {!editing&&!walking&&<div className={'walker-control '+(placingWalker?'placing':'')}><button className="walker-person" draggable onDragStart={e=>{e.dataTransfer.setData('application/x-gnarly-walker','person');e.dataTransfer.setData('text/plain','Gnarly walk position');e.dataTransfer.effectAllowed='copy';e.dataTransfer.setDragImage(e.currentTarget,25,25);setDraggingWalker(true)}} onDragEnd={()=>setDraggingWalker(false)} onClick={()=>walker?(setFloor(walker.floorId),setWalking(true)):setPlacingWalker(value=>!value)} aria-label={walker?'Enter walk mode from the person marker':'Drag person onto a floor or click to place'}><PersonStanding size={45} strokeWidth={2.2}/></button><span>{walker?'Walk from here':'Drag person inside'}</span><small>{walker?'Drag person to move':'or click person, then floor'}</small></div>}
      {walking&&<><div className="walk-hud"><Footprints size={18}/><div><strong>Walk mode</strong><span>Drag to look · WASD or arrows to move · Shift to hurry</span></div><button onClick={()=>setWalking(false)}>Exit</button></div><div className="walk-pad" aria-label="Walk controls"><button onPointerDown={()=>walkKey('KeyW',true)} onPointerUp={()=>walkKey('KeyW',false)} onPointerLeave={()=>walkKey('KeyW',false)} aria-label="Walk forward">↑</button><button onPointerDown={()=>walkKey('KeyA',true)} onPointerUp={()=>walkKey('KeyA',false)} onPointerLeave={()=>walkKey('KeyA',false)} aria-label="Walk left">←</button><button onPointerDown={()=>walkKey('KeyS',true)} onPointerUp={()=>walkKey('KeyS',false)} onPointerLeave={()=>walkKey('KeyS',false)} aria-label="Walk backward">↓</button><button onPointerDown={()=>walkKey('KeyD',true)} onPointerUp={()=>walkKey('KeyD',false)} onPointerLeave={()=>walkKey('KeyD',false)} aria-label="Walk right">→</button></div></>}
      {draggingWalker&&<div className="walker-drop-hint">Drop onto a floor to start walking</div>}{placingWalker&&<div className="editor-hint walker-place-hint">Click a floor to place the person</div>}
      {!building.demo&&!scan&&<div className="geometry-notice">Scan walls unavailable. Only confirmed connections can be routed; they remain unverified.</div>}{editing&&<div className="editor-hint">{tool==='add'?'Click the floor to add a waypoint':tool==='move'?'Click the floor to move the selected waypoint':'Click a waypoint to edit it'}</div>}
      <div className="viewer-toolbar">{building.zones&&building.zones.length>1&&<div className="floor-switch"><Building2 size={17}/><select aria-label="Scan zone" value={building.zoneId} onChange={e=>{const zone=building.zones?.find(item=>item.id===e.target.value);if(zone)zoneChange(zone)}}>{building.zones.map(zone=><option key={zone.id} value={zone.id}>{zone.name}</option>)}</select></div>}<div className="floor-switch"><Layers size={17}/><select aria-label="Visible floor" value={floor} onChange={e=>{setFloor(e.target.value);setWalking(false)}}><option value="all">All floors</option>{graph.floors.map(item=><option key={item.id} value={item.id}>{item.name||item.id}</option>)}</select></div><button onClick={()=>walking?setWalking(false):setReset(value=>value+1)} aria-label={walking?'Exit walk mode':'Reset camera view'}><RotateCcw size={17}/></button></div></div>
    <aside className="route-panel workspace-panel"><div className="route-eyebrow">PLAN & EDIT</div><h2>{editing?'Waypoints':'Where to?'}</h2><div className={'sync-status '+status}>{status==='saved'?(mode==='firebase'?'Saved to Firebase':'Saved locally · not synced'):status==='unsynced'?'Unsaved changes':status==='saving'?'Saving…':status==='conflict'?'Remote conflict':status==='failed'?'Save failed · edits preserved':'Loading graph…'}</div>
      <div className="mode-row"><label>Data mode<select aria-label="Data mode" value={mode} onChange={e=>modeChange(e.target.value as Mode)}><option value="local">Local test · browser only</option>{!building.demo&&canEditFirebase()&&<option value="firebase">Firebase · shared graph</option>}</select></label><button onClick={()=>{setEditing(!editing);setTool('select');setWalking(false);setPlacingWalker(false)}}>{editing?'Done editing':'Edit waypoints'}</button></div>
      {remote&&<div className="conflict-box"><strong>Graph changed elsewhere</strong><p>Your draft has {graph.nodes.length} waypoints and {graph.edges.length} connections. The current shared graph has {remote.graph.nodes.length} waypoints and {remote.graph.edges.length} connections. Your draft is preserved.</p><button onClick={()=>resolveConflict(false)}>Keep draft as next version</button><button onClick={()=>resolveConflict(true)}>Discard draft and load remote</button></div>}{error&&<div className="error">{error}</div>}{notice&&<div className="notice">{notice}</div>}
      {editing?<><div className="editor-tools"><button className={tool==='select'?'active':''} onClick={()=>setTool('select')}>Select</button><button className={tool==='add'?'active':''} onClick={()=>setTool('add')}>Add</button><button className={tool==='move'?'active':''} disabled={!selected} onClick={()=>setTool('move')}>Move</button></div>
        <Picker caption="Selected waypoint" nodes={graph.nodes} value={selectedId} change={setSelectedId}/>{selected&&<div className="waypoint-form"><small>ID · {selected.id}</small><label>Name<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><div className="form-pair"><label>Type<select value={form.type} onChange={e=>setForm({...form,type:e.target.value})}>{types.map(type=><option key={type}>{type}</option>)}</select></label><label>Floor<select value={form.floor} onChange={e=>setForm({...form,floor:e.target.value})}>{graph.floors.map(item=><option key={item.id} value={item.id}>{item.name||item.id}</option>)}</select></label></div><div className="coordinate-row">{(['x','y','z'] as const).map(axis=><label key={axis}>{axis.toUpperCase()} (m)<input type="number" step="0.01" value={form[axis]} onChange={e=>setForm({...form,[axis]:e.target.value})}/></label>)}</div><button className="primary" onClick={applyForm}>Apply waypoint</button><button className="delete-waypoint" onClick={remove}>Delete waypoint</button></div>}
        {selected&&<div className="connections"><h3>Connections</h3>{graph.edges.filter(edge=>edge.from===selected.id||edge.to===selected.id).map((edge,index)=><div className="connection" key={index}><span>{edge.from===selected.id?edge.to:edge.from}<small> · {edge.meters.toFixed(1)} m · {checkEdge(edge,graph,scan).status}</small></span><button aria-label={'Remove connection '+index} onClick={()=>change(disconnectWaypoints(graph,edge.from,edge.to))}><X size={14}/></button></div>)}<label>Connect to<select value={target} onChange={e=>setTarget(e.target.value)}><option value="">Choose waypoint</option>{graph.nodes.filter(node=>node.id!==selected.id).map(node=><option key={node.id} value={node.id}>{title(node)}</option>)}</select></label><button disabled={!target} onClick={()=>{try{if(!scan?.floors?.length&&!window.confirm('No scan is available to check walls. Confirm that you have physically verified this connection is walkable.'))return;change(connectWaypoints(graph,selected.id,target,scan),'Connection added.');setTarget('')}catch(e){setError(String(e))}}}>Add connection</button></div>}
        <div className="graph-health">{blocked.length} blocked · {unverified} unverified connections{blocked.length>0&&<button onClick={()=>{if(window.confirm('Remove '+blocked.length+' blocked connections?'))change({...graph,edges:graph.edges.filter(edge=>checkEdge(edge,graph,scan).status!=='blocked')},'Blocked connections removed.')}}>Remove blocked</button>}</div>{issues.length>0&&<div className="error">{issues.slice(0,3).join('; ')}</div>}{newBlocked.length>0&&<div className="error">{newBlocked.length} new blocked connection(s) must be removed before saving.</div>}
        <div className="save-actions"><button className="primary" disabled={!dirty||status==='saving'||Boolean(issues.length)||Boolean(newBlocked.length)||Boolean(remote)} onClick={()=>void save()}><Save size={15}/> Save {mode==='firebase'?'to Firebase':'locally'}</button><button onClick={cancel} disabled={!dirty}>Cancel edits</button></div>
      </>:<><Picker caption="Starting point" nodes={graph.nodes} value={start} change={id=>{setStart(id);setStep(0)}}/><Picker caption="Destination" nodes={graph.nodes} value={destination} change={id=>{setDestination(id);setStep(0)}}/>{selected&&<div className="selected-actions"><strong>{title(selected)}</strong><button onClick={()=>{setStart(selected.id);setShowRoute(true);setStep(0)}}>Set as start</button><button onClick={()=>{setDestination(selected.id);setShowRoute(true);setStep(0)}}>Set as destination</button></div>}<button className="primary" onClick={()=>{setShowRoute(true);setStep(0);setFloor('all')}}>Show route <ArrowRight size={17}/></button>{route&&(route.ok?<div className="route-result"><div className="route-distance"><strong>{route.distance.toFixed(1)} m</strong><span>{route.floorTransitions} FLOOR TRANSITIONS</span></div><p>{route.nodes.map(node=>node.label||node.id).join(' → ')}</p>{route.unverifiedEdges>0&&<div className="notice">{route.unverifiedEdges} connection(s) are confirmed but cannot be checked against a scan.</div>}<button className="preview" onClick={()=>{setStep(0);setFloor(route.nodes[0].floor);setPlaying(true)}}>{playing?'Playing preview…':'Preview route'}</button></div>:<div className="notice">{route.message}</div>)}<div className="route-foot">Routes follow graph connections that pass floor and wall checks. No straight-line shortcut is drawn.</div></>}
    </aside></main>;
}
