import { useEffect, useMemo, useRef, useState } from 'react';
import { ArrowLeft, ArrowRight, Building2, Footprints, Layers, PersonStanding, RotateCcw, Save, X } from 'lucide-react';
import Viewer, { type DropRequest, type WalkLocation } from './Viewer';
import type { Building, Graph, Node, ZoneView } from './data.ts';
import { canEditFirebase } from './firebase.ts';
import { checkEdge, pointOnFloor } from './geometry.ts';
import { addWaypoint, connectWaypoints, deleteWaypoint, disconnectWaypoints, updateWaypoint, validateGraph } from './graphEdit.ts';
import { copyGraph, createGraphStore, type GraphSnapshot } from './graphStore.ts';
import { findRoute } from './routing.ts';

type Props = { building: Building; onBack: () => void; onUpdate: (building: Building) => void; onDirtyChange?: (dirty:boolean)=>void };
type Mode = 'local' | 'firebase';
type Tool = 'select' | 'add' | 'move';
type Status = 'loading' | 'saved' | 'unsynced' | 'saving' | 'failed' | 'conflict';
const types = ['entrance','hallway','stairs','destination','door','opening','waypoint'];
const draftKey = (b: Building, mode: Mode) => ['gnarly-draft',mode,b.id,b.activeVersion||'sample',b.zoneId||'root'].join(':');
const waypointForm = (node: Node) => ({name:node.label||'',type:node.type,floor:node.floor,x:String(node.position[0]),y:String(node.position[1]),z:String(node.position[2])});
const title = (node: Node) => (node.label ? node.label + ' · ' : '') + node.id;
function Picker({ caption, nodes, value, change }: { caption: string; nodes: Node[]; value: string; change: (value: string) => void }) {
  const [query,setQuery] = useState('');
  const visible=nodes.filter(node=>title(node).toLowerCase().includes(query.toLowerCase()));
  return <label className="waypoint-picker">{caption}<input aria-label={'Search '+caption} placeholder="Search waypoints" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label={caption} value={value} onChange={e=>change(e.target.value)}><option value="">Choose waypoint</option>{visible.map(node=><option key={node.id} value={node.id}>{title(node)}</option>)}{value&&!visible.some(node=>node.id===value)&&nodes.some(node=>node.id===value)&&<option value={value}>{title(nodes.find(node=>node.id===value)!)}</option>}</select></label>;
}
export default function BuildingWorkspace({building,onBack,onUpdate,onDirtyChange}:Props) {
  const [mode,setMode]=useState<Mode>(building.demo||!canEditFirebase()?'local':'firebase');
  const store=useMemo(()=>createGraphStore(building,mode),[building.id,building.activeVersion,building.zoneId,mode]);
  const [base,setBase]=useState<GraphSnapshot|null>(null),[draft,setDraft]=useState<Graph|null>(null),[remote,setRemote]=useState<GraphSnapshot|null>(null);
  const baseRef=useRef<GraphSnapshot|null>(null),savingRef=useRef(false),loadedKey=useRef<string|null>(null);
  const [status,setStatus]=useState<Status>('loading'),[error,setError]=useState(''),[notice,setNotice]=useState('');
  const [editing,setEditing]=useState(false),[tool,setTool]=useState<Tool>('select'),[selectedId,setSelectedId]=useState(''),[target,setTarget]=useState('');
  const [floor,setFloor]=useState('all'),[start,setStart]=useState(''),[destination,setDestination]=useState(''),[showRoute,setShowRoute]=useState(false),[step,setStep]=useState(0),[playing,setPlaying]=useState(false),[reset,setReset]=useState(0);
  const [walker,setWalker]=useState<WalkLocation|null>(null),[walking,setWalking]=useState(false),[placingWalker,setPlacingWalker]=useState(false),[walkDrop,setWalkDrop]=useState<DropRequest|null>(null),[draggingWalker,setDraggingWalker]=useState(false);
  const [form,setForm]=useState({name:'',type:'waypoint',floor:'',x:'',y:'',z:''});
  const graph=draft||building.graph!; const scan=building.scan; const key=draftKey(building,mode);
  const dirty=Boolean(base&&draft&&JSON.stringify(base.graph)!==JSON.stringify(draft));
  const selected=graph.nodes.find(node=>node.id===selectedId);
  const formDirty=Boolean(selected&&JSON.stringify(form)!==JSON.stringify(waypointForm(selected)));
  const pending=dirty||formDirty;
  const current=useRef({base,draft,pending});current.current={base,draft,pending};
  const route=useMemo(()=>showRoute?findRoute({graph,startId:start,destinationId:destination,options:{scan}}):null,[graph,start,destination,showRoute,scan]);
  const blocked=useMemo(()=>graph.edges.filter(edge=>checkEdge(edge,graph,scan).status==='blocked'),[graph,scan]);
  const newBlocked=useMemo(()=>{const previous=new Set((base?.graph.edges||[]).filter(edge=>checkEdge(edge,base!.graph,scan).status==='blocked').map(edge=>JSON.stringify(edge)));return blocked.filter(edge=>!previous.has(JSON.stringify(edge)))},[base,blocked,scan]);
  const unverified=useMemo(()=>graph.edges.filter(edge=>checkEdge(edge,graph,scan).status==='unverified').length,[graph,scan]);
  const issues=useMemo(()=>validateGraph(graph),[graph]);
  useEffect(()=>onDirtyChange?.(pending),[pending,onDirtyChange]);
  useEffect(()=>{
    let live=true,receivedSubscription=false;baseRef.current=null;loadedKey.current=null;setStatus('loading');setBase(null);setDraft(null);setRemote(null);setError('');setEditing(false);setShowRoute(false);setPlaying(false);setStep(0);setFloor('all');setSelectedId('');setTarget('');setWalker(null);setWalking(false);setPlacingWalker(false);setNotice('');
    function received(snapshot:GraphSnapshot){
      if(!live||savingRef.current||baseRef.current?.revision===snapshot.revision)return;loadedKey.current=key;
      if(baseRef.current && current.current.pending){setRemote(snapshot);setStatus('conflict');return;}
      if(!baseRef.current){
        try{
          const saved=sessionStorage.getItem(key)||localStorage.getItem(key);
          if(saved){
            const local=JSON.parse(saved) as {base:GraphSnapshot;graph:Graph;form?:typeof form;selectedId?:string};
            if(!local.base?.graph || !local.graph?.nodes || !local.graph?.edges)throw Error('Invalid draft');
            baseRef.current=local.base;setBase(local.base);setDraft(local.graph);
            if(local.form&&local.selectedId){setSelectedId(local.selectedId);setForm(local.form);restoredForm.current=local.form;setEditing(true)}
            setRemote(local.base.revision===snapshot.revision?null:snapshot);setStatus(local.base.revision===snapshot.revision?'unsynced':'conflict');
            setStart(local.graph.nodes.find(node=>node.type==='entrance')?.id||local.graph.nodes[0]?.id||'');
            setDestination(local.graph.nodes.find(node=>node.type==='destination')?.id||local.graph.nodes.at(-1)?.id||'');
            setNotice('Recovered your unsaved draft in this tab.');
            localStorage.removeItem(key);return;
          }
        }catch{setError('The stored draft could not be restored. The saved graph has been loaded.');sessionStorage.removeItem(key)}
      }
      baseRef.current=snapshot;setBase(snapshot);setDraft(copyGraph(snapshot.graph));setRemote(null);setStatus('saved');
      setStart(previous=>snapshot.graph.nodes.some(node=>node.id===previous)?previous:snapshot.graph.nodes.find(node=>node.type==='entrance')?.id||snapshot.graph.nodes[0]?.id||'');
      setDestination(previous=>snapshot.graph.nodes.some(node=>node.id===previous)?previous:snapshot.graph.nodes.find(node=>node.type==='destination')?.id||snapshot.graph.nodes.at(-1)?.id||'');
    }
    store.load().then(snapshot=>{if(!receivedSubscription)received(snapshot)}).catch(e=>{if(live){setError(String(e));setStatus('failed')}});
    const unsubscribe=store.subscribe(snapshot=>{receivedSubscription=true;received(snapshot)},e=>{if(live)setError(e.message)});
    return()=>{live=false;unsubscribe()};
  },[store,key]);
  const restoredForm=useRef<typeof form|null>(null);
  useEffect(()=>{if(!base||!draft||loadedKey.current!==key)return;try{if(pending)sessionStorage.setItem(key,JSON.stringify({base,graph:draft,form,selectedId}));else sessionStorage.removeItem(key)}catch{setError('Browser draft backup is unavailable. Keep this tab open until you save.')}},[base,draft,pending,key,form,selectedId]);
  useEffect(()=>{if(!pending)return;const guard=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue=''};window.addEventListener('beforeunload',guard);return()=>window.removeEventListener('beforeunload',guard)},[pending]);
  useEffect(()=>{if(!playing||!route?.ok)return;const timer=window.setTimeout(()=>{if(step>=route.nodes.length-1){setPlaying(false);return}setStep(step+1);setFloor(route.nodes[step+1].floor)},850);return()=>window.clearTimeout(timer)},[playing,route,step]);
  useEffect(()=>{if(restoredForm.current){setForm(restoredForm.current);restoredForm.current=null}else if(selected)setForm(waypointForm(selected))},[selectedId,selected?.position,selected?.label,selected?.type,selected?.floor]);
  useEffect(()=>{setStep(0);setPlaying(false)},[route]);
  function chooseWaypoint(id:string){if(formDirty&&!window.confirm('Discard the unapplied waypoint fields? Apply waypoint first to keep them.'))return;setSelectedId(id);setTarget('');setPlaying(false)}
  function change(next:Graph,message=''){setDraft(next);setNotice(message);setError('');setPlaying(false);setStep(0);if(!remote)setStatus(base&&JSON.stringify(base.graph)===JSON.stringify(next)?'saved':'unsynced')}
  function leave(){if(pending&&!window.confirm('Leave with unsaved edits? Applied edits and waypoint fields will remain in this tab.'))return;onBack()}
  function zoneChange(zone:ZoneView){if(pending&&!window.confirm('Switch zones? Your unsaved draft will remain in this tab.'))return;onUpdate({...building,zoneId:zone.id,graph:zone.graph,scan:zone.scan,graphPath:zone.graphPath,notice:zone.notice})}
  function modeChange(next:Mode){if(next===mode)return;if(pending&&!window.confirm('Switch data modes? Your unsaved draft will remain in this tab.'))return;setMode(next)}
  function floorPick(position:[number,number,number],floorId:string){
    if(!editing||tool==='select')return;
    if(formDirty&&!window.confirm('Discard the unapplied waypoint fields before placing this waypoint?'))return;
    const nearest=graph.nodes.filter(node=>node.floor===floorId).sort((a,b)=>Math.hypot(a.position[0]-position[0],a.position[2]-position[2])-Math.hypot(b.position[0]-position[0],b.position[2]-position[2]))[0];
    const point:[number,number,number]=[position[0],nearest?.position[1]??position[1],position[2]];
    if(!pointOnFloor(point,floorId,graph,scan)){setError('Pick a position on the displayed floor.');return}
    try{if(tool==='add'){const id='wp-'+crypto.randomUUID().slice(0,8);change(addWaypoint(graph,{id,floor:floorId,type:'waypoint',position:point,label:'',source:'manual'},scan),'Waypoint added. Connect it to walkable neighbors.');setSelectedId(id)}
    else if(selected){const result=updateWaypoint(graph,{...selected,floor:floorId,position:point},scan);if(result.removedEdges.length&&!window.confirm('Moving removes '+result.removedEdges.length+' blocked connection(s). Continue?'))return;change(result.graph,result.removedEdges.length+' affected connection(s) removed.')}setTool('select')}catch(e){setError(String(e))}
  }
  function placeWalker(location:WalkLocation|null){
    setDraggingWalker(false);
    if(!location){setError('Drop the person onto a visible floor inside the building.');return}
    const floorInfo=graph.floors.find(item=>item.id===location.floorId);
    const position:[number,number,number]=[location.position[0],scan?.floors?.length?location.position[1]:floorInfo?.elevation??location.position[1],location.position[2]];
    if(!pointOnFloor(position,location.floorId,graph,scan)){setError('Drop the person onto a walkable part of the floor.');return}
    setWalker({position,floorId:location.floorId});setFloor(location.floorId);setWalking(true);setPlacingWalker(false);setPlaying(false);setError('');
  }
  function viewerFloorPick(position:[number,number,number],floorId:string){if(placingWalker)placeWalker({position,floorId});else floorPick(position,floorId)}
  function walkKey(code:string,down:boolean){window.dispatchEvent(new KeyboardEvent(down?'keydown':'keyup',{code,bubbles:true}))}
  function applyForm(){if(!selected)return;const position=[Number(form.x),Number(form.y),Number(form.z)] as [number,number,number];if([form.x,form.y,form.z].some(x=>x.trim()==='')||!position.every(Number.isFinite)){setError('Enter valid X, Y, Z coordinates.');return}
    try{const result=updateWaypoint(graph,{...selected,label:form.name.trim()||null,type:form.type,floor:form.floor,position},scan);if(result.removedEdges.length&&!window.confirm('This edit removes '+result.removedEdges.length+' blocked connection(s). Continue?'))return;change(result.graph,result.removedEdges.length?result.removedEdges.length+' blocked connection(s) removed.':'Waypoint updated.')}catch(e){setError(String(e))}}
  function remove(){if(!selected)return;const count=graph.edges.filter(edge=>edge.from===selected.id||edge.to===selected.id).length;if(!window.confirm('Delete '+selected.id+(count?' and its '+count+' connection(s)':'')+'?'))return;change(deleteWaypoint(graph,selected.id).graph,'Waypoint deleted.');setSelectedId('')}
  async function save(){if(!base||!draft||savingRef.current||formDirty)return;if(issues.length||newBlocked.length){setError('Resolve '+issues.length+' graph error(s) and '+newBlocked.length+' newly blocked connection(s) before saving.');return}if(remote){setStatus('conflict');return}savingRef.current=true;setStatus('saving');setError('');try{const saved=await store.save(draft,base);baseRef.current=saved;setBase(saved);setDraft(copyGraph(saved.graph));setStatus('saved');sessionStorage.removeItem(key);setNotice(mode==='firebase'?'Saved to Firebase.':'Saved in this browser only · not synced.');if(mode==='firebase')onUpdate({...building,graph:saved.graph,graphPath:saved.path})}catch(e){setStatus('failed');setError(String(e))}finally{savingRef.current=false;void store.load().then(latest=>{if(latest.revision!==baseRef.current?.revision){setRemote(latest);setStatus('conflict')}}).catch(()=>{})}}
  function cancel(){const saved=remote||base;if(!saved)return;baseRef.current=saved;setBase(saved);setDraft(copyGraph(saved.graph));setSelectedId('');setRemote(null);setError('');setNotice('Restored the latest saved graph.');setStatus('saved');sessionStorage.removeItem(key)}
  function resolveConflict(useRemote:boolean){if(!remote)return;if(useRemote){if(!window.confirm('Discard your draft and load the remote graph?'))return;baseRef.current=remote;setBase(remote);setDraft(copyGraph(remote.graph));sessionStorage.removeItem(key);setSelectedId('');setStatus('saved')}
    else{if(!window.confirm('This will keep your complete draft as the next graph. Changes made in the remote graph since you started will not appear in it. The previous graph file remains in Storage. Continue only after reviewing both versions.'))return;baseRef.current=remote;setBase(remote);setStatus('unsynced');setNotice('Your draft is based on the latest revision. Review all connections before saving; the prior graph file remains in Storage.')}setRemote(null)}
  return <main className="inside"><div className="viewer-top"><div><button className="back" disabled={status==='saving'} onClick={leave}><ArrowLeft size={17}/> Back to map</button><div className="viewer-title"><span>BUILDING EXPLORER</span><h1>{building.name}</h1></div></div><div className="viewer-badge"><span/> {building.demo?'SAMPLE EXPERIENCE':'LIVE BUILDING'}</div></div>
    <div className={'viewer '+(draggingWalker?'walker-dragging ':'')+(walking?'walking-view':'')} onDragOver={e=>{if(e.dataTransfer.types.includes('application/x-gnarly-walker')){e.preventDefault();e.dataTransfer.dropEffect='copy';setDraggingWalker(true)}}} onDragLeave={e=>{if(!e.currentTarget.contains(e.relatedTarget as globalThis.Node|null))setDraggingWalker(false)}} onDrop={e=>{if(!e.dataTransfer.types.includes('application/x-gnarly-walker'))return;e.preventDefault();setWalkDrop({clientX:e.clientX,clientY:e.clientY,id:Date.now()})}}>
      <Viewer graph={graph} scan={scan} illustrative={Boolean(building.demo)} floor={floor} selected={selectedId||destination} onSelect={id=>{if(status!=='saving')chooseWaypoint(id)}} path={route?.ok?route.nodes:[]} step={step} reset={reset} editing={editing} onFloorPick={status!=='saving'&&(editing||placingWalker)?viewerFloorPick:undefined} walker={walker} walking={walking} dropRequest={walkDrop} onWalkerDrop={placeWalker} onWalkerMove={setWalker}/>
      {!editing&&!walking&&<div className={'walker-control '+(placingWalker?'placing':'')}><button className="walker-person" draggable onDragStart={e=>{e.dataTransfer.setData('application/x-gnarly-walker','person');e.dataTransfer.setData('text/plain','Gnarly walk position');e.dataTransfer.effectAllowed='copy';e.dataTransfer.setDragImage(e.currentTarget,25,25);setDraggingWalker(true)}} onDragEnd={()=>setDraggingWalker(false)} onClick={()=>walker?(setFloor(walker.floorId),setWalking(true)):setPlacingWalker(value=>!value)} aria-label={walker?'Enter walk mode from the person marker':'Drag person onto a floor or click to place'}><PersonStanding size={45} strokeWidth={2.2}/></button><span>{walker?'Walk from here':'Drag person inside'}</span><small>{walker?'Drag person to move':'or click person, then floor'}</small></div>}
      {walking&&<><div className="walk-hud"><Footprints size={18}/><div><strong>Walk mode</strong><span>Drag to look · W/S or ↑/↓ move · A/D or ←/→ turn</span></div><button onClick={()=>setWalking(false)}>Exit</button></div><div className="walk-pad" aria-label="Walk controls"><button onPointerDown={e=>{e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);walkKey('KeyW',true)}} onPointerUp={()=>walkKey('KeyW',false)} onPointerCancel={()=>walkKey('KeyW',false)} aria-label="Walk forward">↑</button><button onPointerDown={e=>{e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);walkKey('KeyA',true)}} onPointerUp={()=>walkKey('KeyA',false)} onPointerCancel={()=>walkKey('KeyA',false)} aria-label="Turn left">↶</button><button onPointerDown={e=>{e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);walkKey('KeyS',true)}} onPointerUp={()=>walkKey('KeyS',false)} onPointerCancel={()=>walkKey('KeyS',false)} aria-label="Walk backward">↓</button><button onPointerDown={e=>{e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);walkKey('KeyD',true)}} onPointerUp={()=>walkKey('KeyD',false)} onPointerCancel={()=>walkKey('KeyD',false)} aria-label="Turn right">↷</button></div></>}
      {draggingWalker&&<div className="walker-drop-hint">Drop onto a floor to start walking</div>}{placingWalker&&<div className="editor-hint walker-place-hint">Click a floor to place the person <button onClick={()=>setPlacingWalker(false)}>Cancel</button></div>}
      {!building.demo&&!scan&&<div className="geometry-notice">Scan walls unavailable. Only confirmed connections can be routed; they remain unverified.</div>}{editing&&<div className="editor-hint">{tool==='add'?'Click the floor to add a waypoint':tool==='move'?'Click the floor to move the selected waypoint':'Click a waypoint to edit it'}</div>}
      <div className="viewer-toolbar">{building.zones&&building.zones.length>1&&<div className="floor-switch"><Building2 size={17}/><select aria-label="Scan zone" disabled={status==='saving'} value={building.zoneId} onChange={e=>{const zone=building.zones?.find(item=>item.id===e.target.value);if(zone)zoneChange(zone)}}>{building.zones.map(zone=><option key={zone.id} value={zone.id}>{zone.name}</option>)}</select></div>}<div className="floor-switch"><Layers size={17}/><select aria-label="Visible floor" value={floor} onChange={e=>{setFloor(e.target.value);setWalking(false);setPlaying(false)}}><option value="all">All floors</option>{graph.floors.map(item=><option key={item.id} value={item.id}>{item.name||item.id}</option>)}</select></div><button onClick={()=>walking?setWalking(false):setReset(value=>value+1)} aria-label={walking?'Exit walk mode':'Reset camera view'}><RotateCcw size={17}/></button></div></div>
    <aside className="route-panel workspace-panel"><div className="route-eyebrow">PLAN & EDIT</div><h2>{editing?'Waypoints':'Where to?'}</h2><div role="status" className={'sync-status '+(formDirty&&status==='saved'?'unsynced':status)}>{formDirty&&status==='saved'?'Unapplied waypoint changes':status==='saved'?(mode==='firebase'?'Saved to Firebase':'Saved locally · not synced'):status==='unsynced'?'Unsaved changes':status==='saving'?'Saving…':status==='conflict'?'Remote conflict':status==='failed'?(base?'Save failed · edits preserved':'Unable to load graph'):'Loading graph…'}</div>
      <div className="mode-row"><label>Data mode<select aria-label="Data mode" disabled={status==='saving'} value={mode} onChange={e=>modeChange(e.target.value as Mode)}><option value="local">Local test · browser only</option>{!building.demo&&canEditFirebase()&&<option value="firebase">Firebase · shared graph</option>}</select></label><button disabled={!base||status==='saving'} onClick={()=>{if(formDirty&&!window.confirm('Discard the unapplied waypoint fields?'))return;if(selected)setForm(waypointForm(selected));setEditing(!editing);setTool('select');setWalking(false);setPlacingWalker(false)}}>{editing?'Done editing':'Edit waypoints'}</button></div>
      {!base&&status==='failed'&&<button className="secondary" onClick={()=>{setStatus('loading');setMode('local');if(mode==='local')void store.load().then(snapshot=>{loadedKey.current=key;baseRef.current=snapshot;setBase(snapshot);setDraft(copyGraph(snapshot.graph));setStatus('saved');setError('')}).catch(e=>{setStatus('failed');setError(String(e))})}}>Open local test mode</button>}{remote&&<div className="conflict-box"><strong>Graph changed elsewhere</strong><p>Your draft has {graph.nodes.length} waypoints and {graph.edges.length} connections. The current shared graph has {remote.graph.nodes.length} waypoints and {remote.graph.edges.length} connections. Your draft is preserved.</p><button onClick={()=>resolveConflict(false)}>Keep draft as next version</button><button onClick={()=>resolveConflict(true)}>Discard draft and load remote</button></div>}{error&&<div role="alert" className="error">{error}</div>}{notice&&<div className="notice">{notice}</div>}
      {editing?<fieldset className="editor-fields" disabled={status==='saving'}><legend className="sr-only">Waypoint editor</legend><div className="editor-tools"><button className={tool==='select'?'active':''} onClick={()=>setTool('select')}>Select</button><button className={tool==='add'?'active':''} onClick={()=>setTool('add')}>Add</button><button className={tool==='move'?'active':''} disabled={!selected} onClick={()=>setTool('move')}>Move</button></div>
        <Picker caption="Selected waypoint" nodes={graph.nodes} value={selectedId} change={chooseWaypoint}/>{selected&&<div className="waypoint-form"><small>ID · {selected.id}</small><label>Name<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><div className="form-pair"><label>Type<select value={form.type} onChange={e=>setForm({...form,type:e.target.value})}>{!types.includes(form.type)&&<option>{form.type}</option>}{types.map(type=><option key={type}>{type}</option>)}</select></label><label>Floor<select value={form.floor} onChange={e=>setForm({...form,floor:e.target.value})}>{graph.floors.map(item=><option key={item.id} value={item.id}>{item.name||item.id}</option>)}</select></label></div><div className="coordinate-row">{(['x','y','z'] as const).map(axis=><label key={axis}>{axis.toUpperCase()} (m)<input type="number" step="0.01" value={form[axis]} onChange={e=>setForm({...form,[axis]:e.target.value})}/></label>)}</div><button className="primary" disabled={!formDirty} onClick={applyForm}>Apply waypoint</button>{formDirty&&<small className="pending-fields">Apply these fields before saving the graph.</small>}<button className="delete-waypoint" onClick={remove}>Delete waypoint</button></div>}
        {selected&&<div className="connections"><h3>Connections</h3>{graph.edges.filter(edge=>edge.from===selected.id||edge.to===selected.id).map((edge,index)=><div className="connection" key={index}><span>{edge.from===selected.id?edge.to:edge.from}<small> · {edge.meters.toFixed(1)} m · {checkEdge(edge,graph,scan).status}</small></span><button aria-label={'Remove connection '+index} onClick={()=>change(disconnectWaypoints(graph,edge.from,edge.to))}><X size={14}/></button></div>)}<label>Connect to<select value={target} onChange={e=>setTarget(e.target.value)}><option value="">Choose waypoint</option>{graph.nodes.filter(node=>node.id!==selected.id).map(node=><option key={node.id} value={node.id}>{title(node)}</option>)}</select></label><button disabled={!target} onClick={()=>{try{if(!scan?.floors?.length&&!window.confirm('No scan is available to check walls. Confirm that you have physically verified this connection is walkable.'))return;change(connectWaypoints(graph,selected.id,target,scan),'Connection added.');setTarget('')}catch(e){setError(String(e))}}}>Add connection</button></div>}
        <div className="graph-health">{blocked.length} blocked · {unverified} unverified connections{blocked.length>0&&<button onClick={()=>{if(window.confirm('Remove '+blocked.length+' blocked connections?'))change({...graph,edges:graph.edges.filter(edge=>checkEdge(edge,graph,scan).status!=='blocked')},'Blocked connections removed.')}}>Remove blocked</button>}</div>{issues.length>0&&<div className="error">{issues.slice(0,3).join('; ')}</div>}{newBlocked.length>0&&<div className="error">{newBlocked.length} new blocked connection(s) must be removed before saving.</div>}
        <div className="save-actions"><button className="primary" disabled={!dirty||formDirty||status==='saving'||Boolean(issues.length)||Boolean(newBlocked.length)||Boolean(remote)} onClick={()=>void save()}><Save size={15}/> Save {mode==='firebase'?'to Firebase':'locally'}</button><button onClick={cancel} disabled={!pending}>Cancel edits</button></div>
      </fieldset>:<><Picker caption="Starting point" nodes={graph.nodes} value={start} change={id=>{setStart(id);setStep(0)}}/><Picker caption="Destination" nodes={graph.nodes} value={destination} change={id=>{setDestination(id);setStep(0)}}/>{selected&&<div className="selected-actions"><strong>{title(selected)}</strong><button onClick={()=>{setStart(selected.id);setShowRoute(true);setStep(0)}}>Set as start</button><button onClick={()=>{setDestination(selected.id);setShowRoute(true);setStep(0)}}>Set as destination</button></div>}<button className="primary" disabled={!start||!destination||!base} onClick={()=>{setShowRoute(true);setPlaying(false);setStep(0);setFloor('all')}}>Show route <ArrowRight size={17}/></button>{route&&(route.ok?<div className="route-result"><div className="route-distance"><strong>{route.distance.toFixed(1)} m</strong><span>{route.floorTransitions} FLOOR {route.floorTransitions===1?'TRANSITION':'TRANSITIONS'}</span></div><p>{route.nodes.map(node=>node.label||node.id).join(' → ')}</p>{route.unverifiedEdges>0&&<div className="notice">{route.unverifiedEdges} connection(s) are confirmed but cannot be checked against a scan.</div>}<button className="preview" onClick={()=>{if(playing){setPlaying(false);return}setWalking(false);setStep(0);setFloor(route.nodes[0].floor);setPlaying(true)}}>{playing?'Stop preview':'Preview route'} <ArrowRight size={15}/></button><div className="route-progress">{playing?'Previewing: '+(route.nodes[Math.min(step,route.nodes.length-1)].label||route.nodes[Math.min(step,route.nodes.length-1)].id):'Explore each waypoint along your route'}</div></div>:<div className="notice">{route.message}</div>)}{dirty&&<button className="secondary" onClick={()=>setEditing(true)}>Review unsaved edits <Save size={14}/></button>}<div className="route-foot">Routes follow graph connections that pass floor and wall checks. No straight-line shortcut is drawn.</div></>}
    </aside></main>;
}
